name: ICF Capsule – ESP-IDF Tests

on:
  pull_request:
    paths:
      - '**.c'
      - '**.h'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build & test under ESP-IDF

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up ESP-IDF
        uses: espressif/install-esp-idf-action@v1
        with:
          version: v5.2
          target: esp32s3

      - name: Build test project
        run: |
          idf.py set-target esp32s3
          idf.py build

      - name: Run component tests
        run: |
          idf.py test
