name: ICF Capsule – ESP-IDF Tests

on:
  pull_request:
    paths:
      - '**/*.c'
      - '**/*.h'
      - '**/*.cpp'
      - '**/*.hpp'
      - '**/CMakeLists.txt'
      - '.github/workflows/**'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build & test under ESP-IDF

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build icf_decode project
        uses:  espressif/esp-idf-ci-action@v1
        with:
          version: v5.2
          target: esp32s3
          path: 'examples/icf_decode'

      - name: Build test project
        uses:  espressif/esp-idf-ci-action@v1
        with:
          version: v5.2
          target: esp32s3
          path: 'test'